US 11 - Music App API music style generator now fetches new styles
IC-Socaciu/all-access-pass-1 pull request #24
Opened 2023-08-11 14:23 UTC by IC-Socaciu

2023-08-11 15:08 UTC, FelineHuhn requested changes
Hey Ioana, nice progress and I love your new feature 🎉
I left you some suggested code snippets for a better error handling.

2023-08-11 15:08 UTC, FelineHuhn commented on pages/discover.js
> +  }
```suggestion

```

2023-08-11 15:08 UTC, FelineHuhn commented on pages/discover.js
> +    []
```suggestion
if (!response.ok) {
        throw new Error("Failed to fetch data");
      }

      const data = await response.json();
      return data;
    }
```

2023-08-12 05:08 UTC, IC-Socaciu commented on pages/discover.js
> +import { styled } from "styled-components";
Thank you. Corrected :)

2023-08-14 08:28 UTC, merged